In [117]:
import pandas as pd

In [118]:
dataset=pd.read_csv('/content/kidney_disease (1).csv')

In [119]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [120]:
dataset['pcv'] = pd.to_numeric(dataset['pcv'], errors='coerce')
dataset['wc'] = pd.to_numeric(dataset['wc'], errors='coerce')
dataset['rc'] = pd.to_numeric(dataset['rc'], errors='coerce')

In [121]:
dataset.columns

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [122]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              400 non-null    int64
 1   age             391 non-null    float64
 2   bp              388 non-null    float64
 3   sg              353 non-null    float64
 4   al              354 non-null    float64
 5   su              351 non-null    float64
 6   rbc             248 non-null    object
 7   pc              335 non-null    object
 8   pcc             396 non-null    object
 9   ba              396 non-null    object
 10  bgr             356 non-null    float64
 11  bu              381 non-null    float64
 12  sc              383 non-null    float64
 13  sod             313 non-null    float64
 14  pot             312 non-null    float64
 15  hemo            348 non-null    float64
 16  pcv             329 non-null    float64
 17  wc              294 non-null    float64
 18  rc              269 non-null    float64
 19  htn             398 non-null    object
 20  dm              398 non-null    object
 21  cad             398 non-null    object
 22  appet           399 non-null    object
 23  pe              399 non-null    object
 24  ane             399 non-null    object
 25  classification  400 non-null    object
dtypes: float64(14), int64(1), object(11)
memory usage: 81.4+ KB

In [123]:
# Select integer columns
int_cols = dataset.select_dtypes(include=['int64'])
# Select float columns
float_cols = dataset.select_dtypes(include=['float64'])
# Select object (string) columns
object_cols = dataset.select_dtypes(include=['object'])

In [124]:
int_cols

      id
0      0
1      1
2      2
3      3
4      4
..   ...
395  395
396  396
397  397
398  398
399  399

[400 rows x 1 columns]

In [125]:
float_cols

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc
0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,NaN,NaN,15.4,44.0,7800.0,5.2
1,7.0,50.0,1.020,4.0,0.0,NaN,18.0,0.8,NaN,NaN,11.3,38.0,6000.0,NaN
2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,NaN,NaN,9.6,31.0,7500.0,NaN
3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,2.5,11.2,32.0,6700.0,3.9
4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,NaN,NaN,11.6,35.0,7300.0,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55.0,80.0,1.020,0.0,0.0,140.0,49.0,0.5,150.0,4.9,15.7,47.0,6700.0,4.9
396,42.0,70.0,1.025,0.0,0.0,75.0,31.0,1.2,141.0,3.5,16.5,54.0,7800.0,6.2
397,12.0,80.0,1.020,0.0,0.0,100.0,26.0,0.6,137.0,4.4,15.8,49.0,6600.0,5.4
398,17.0,60.0,1.025,0.0,0.0,114.0,50.0,1.0,135.0,4.9,14.2,51.0,7200.0,5.9
399,58.0,80.0,1.025,0.0,0.0,131.0,18.0,1.1,141.0,3.5,15.8,53.0,6800.0,6.1

In [126]:
object_cols

,rbc,pc,pcc,ba,htn,dm,cad,appet,pe,ane,classification
0,NaN,normal,notpresent,notpresent,yes,yes,no,good,no,no,ckd
1,NaN,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
2,normal,normal,notpresent,notpresent,no,yes,no,poor,no,yes,ckd
3,normal,abnormal,present,notpresent,yes,no,no,poor,yes,yes,ckd
4,normal,normal,notpresent,notpresent,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...
395,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
396,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
397,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
398,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd
399,normal,normal,notpresent,notpresent,no,no,no,good,no,no,notckd

In [127]:
float_cols.isnull().sum()

age       9
bp       12
sg       47
al       46
su       49
bgr      44
bu       19
sc       17
sod      87
pot      88
hemo     52
pcv      71
wc      106
rc      131
dtype: int64

In [128]:
from sklearn.preprocessing import StandardScaler

In [129]:
scaler = StandardScaler()
float_cols_sc=scaler.fit_transform(float_cols)

In [130]:
float_cols_sc

array([[-0.20313902,  0.25837332,  0.45407053, ...,  0.56988141,
        -0.20620181,  0.4812952 ],
       [-2.59412412, -1.93685691,  0.45407053, ..., -0.09853564,
        -0.8185587 ,         nan],
       [ 0.61329491,  0.25837332, -1.29769883, ..., -0.87835554,
        -0.30826129,         nan],
       ...,
       [-2.30254057,  0.25837332,  0.45407053, ...,  1.12689562,
        -0.61443974,  0.67671921],
       [-2.01095702, -1.2051135 ,  1.32995521, ...,  1.34970131,
        -0.41032077,  1.16527924],
       [ 0.38002807,  0.25837332,  1.32995521, ...,  1.57250699,
        -0.54640008,  1.36070326]])

In [131]:
from sklearn.impute import KNNImputer

In [132]:
imputer = KNNImputer(n_neighbors=5)
float_cols_imput=imputer.fit_transform(float_cols_sc)

In [133]:
float_cols_imput

array([[-0.20313902,  0.25837332,  0.45407053, ...,  0.56988141,
        -0.20620181,  0.4812952 ],
       [-2.59412412, -1.93685691,  0.45407053, ..., -0.09853564,
        -0.8185587 ,  0.4812952 ],
       [ 0.61329491,  0.25837332, -1.29769883, ..., -0.87835554,
        -0.30826129, -0.53490967],
       ...,
       [-2.30254057,  0.25837332,  0.45407053, ...,  1.12689562,
        -0.61443974,  0.67671921],
       [-2.01095702, -1.2051135 ,  1.32995521, ...,  1.34970131,
        -0.41032077,  1.16527924],
       [ 0.38002807,  0.25837332,  1.32995521, ...,  1.57250699,
        -0.54640008,  1.36070326]])

In [134]:
# Step 3: Inverse scaling back to original scale
data_imputed = scaler.inverse_transform(float_cols_imput)

In [135]:
data_imputed

array([[4.800e+01, 8.000e+01, 1.020e+00, ..., 4.400e+01, 7.800e+03,
        5.200e+00],
       [7.000e+00, 5.000e+01, 1.020e+00, ..., 3.800e+01, 6.000e+03,
        5.200e+00],
       [6.200e+01, 8.000e+01, 1.010e+00, ..., 3.100e+01, 7.500e+03,
        4.160e+00],
       ...,
       [1.200e+01, 8.000e+01, 1.020e+00, ..., 4.900e+01, 6.600e+03,
        5.400e+00],
       [1.700e+01, 6.000e+01, 1.025e+00, ..., 5.100e+01, 7.200e+03,
        5.900e+00],
       [5.800e+01, 8.000e+01, 1.025e+00, ..., 5.300e+01, 6.800e+03,
        6.100e+00]])

In [136]:
float_cols.columns

Index(['age', 'bp', 'sg', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hemo',
       'pcv', 'wc', 'rc'],
      dtype='object')

In [137]:
# Step 4: Convert back to DataFrame
imputed_df = pd.DataFrame(data_imputed,columns=float_cols.columns)
imputed_df.head()

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc
0,48.0,80.0,1.020,1.0,0.0,121.0,36.0,1.2,139.4,4.30,15.4,44.0,7800.0,5.20
1,7.0,50.0,1.020,4.0,0.0,84.8,18.0,0.8,136.0,4.02,11.3,38.0,6000.0,5.20
2,62.0,80.0,1.010,2.0,3.0,423.0,53.0,1.8,133.0,4.52,9.6,31.0,7500.0,4.16
3,48.0,70.0,1.005,4.0,0.0,117.0,56.0,3.8,111.0,2.50,11.2,32.0,6700.0,3.90
4,51.0,80.0,1.010,2.0,0.0,106.0,26.0,1.4,137.4,4.22,11.6,35.0,7300.0,4.60

In [138]:
imputed_df.isnull().sum()

age     0
bp      0
sg      0
al      0
su      0
bgr     0
bu      0
sc      0
sod     0
pot     0
hemo    0
pcv     0
wc      0
rc      0
dtype: int64

In [139]:
object_cols.columns

Index(['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'appet', 'pe', 'ane',
       'classification'],
      dtype='object')

In [140]:
object_cols[["rbc"]].value_counts()

rbc
normal      201
abnormal     47
Name: count, dtype: int64

In [141]:
object_cols[["pc"]].value_counts()

pc
normal      259
abnormal     76
Name: count, dtype: int64

In [142]:
object_cols[["pcc"]].value_counts()

pcc
notpresent    354
present        42
Name: count, dtype: int64

In [143]:
object_cols[["ba"]].value_counts()

ba
notpresent    374
present        22
Name: count, dtype: int64

In [144]:
object_cols[["htn"]].value_counts()

htn
no     251
yes    147
Name: count, dtype: int64

In [145]:
object_cols[["dm"]].value_counts()

dm
no       258
yes      134
\tno       3
\tyes      2
 yes       1
Name: count, dtype: int64

In [146]:
object_cols[["cad"]].value_counts()

cad
no      362
yes      34
\tno      2
Name: count, dtype: int64

In [147]:
object_cols[["appet"]].value_counts()

appet
good     317
poor      82
Name: count, dtype: int64

In [148]:
object_cols[["pe"]].value_counts()

pe
no     323
yes     76
Name: count, dtype: int64

In [149]:
object_cols[["ane"]].value_counts()

ane
no     339
yes     60
Name: count, dtype: int64

In [150]:
object_cols[["classification"]].value_counts()

classification
ckd               248
notckd            150
ckd\t               2
Name: count, dtype: int64

In [151]:
object_cols['dm'] = object_cols['dm'].str.strip()
object_cols['cad'] = object_cols['cad'].str.strip()

In [152]:
object_cols['classification'] = object_cols['classification'].str.strip()

In [153]:
object_cols[["classification"]].value_counts()

classification
ckd               250
notckd            150
Name: count, dtype: int64

In [154]:
object_cols[["cad"]].value_counts()

cad
no     364
yes     34
Name: count, dtype: int64

In [155]:
object_cols[["dm"]].value_counts()

dm
no     261
yes    137
Name: count, dtype: int64

In [156]:
object_cols.isnull().sum()

rbc               152
pc                 65
pcc                 4
ba                  4
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [157]:
dummy= pd.get_dummies(object_cols["rbc"],drop_first=True,dtype=int,dummy_na=True)

In [158]:
dummy

     normal  NaN
0         0    1
1         0    1
2         1    0
3         1    0
4         1    0
..      ...  ...
395       1    0
396       1    0
397       1    0
398       1    0
399       1    0

[400 rows x 2 columns]

In [159]:
import numpy as np

In [160]:
dummy = dummy.rename(columns={np.nan: 'nan_col'})
# Apply the condition
dummy.loc[dummy['nan_col'] == 1, 'normal'] = np.nan
object_cols[["rbc"]]=dummy[["normal"]]

In [161]:
object_cols[["rbc"]].isnull().sum()

rbc    152
dtype: int64

In [162]:
object_cols[["rbc"]].value_counts()

rbc
1.0    201
0.0     47
Name: count, dtype: int64

In [163]:
dummy= pd.get_dummies(object_cols["pc"],drop_first=True,dtype=int,dummy_na=True)

In [164]:
dummy

     normal  NaN
0         1    0
1         1    0
2         1    0
3         0    0
4         1    0
..      ...  ...
395       1    0
396       1    0
397       1    0
398       1    0
399       1    0

[400 rows x 2 columns]

In [165]:
dummy = dummy.rename(columns={np.nan: 'nan_col'})
# Apply the condition
dummy.loc[dummy['nan_col'] == 1, 'normal'] = np.nan
object_cols[["pc"]]=dummy[["normal"]]

In [166]:
object_cols[["pc"]].isnull().sum()

pc    65
dtype: int64

In [167]:
object_cols[["pc"]].value_counts()

pc
1.0    259
0.0     76
Name: count, dtype: int64

In [168]:
dummy= pd.get_dummies(object_cols["pcc"],drop_first=True,dtype=int,dummy_na=True)

In [169]:
dummy

     present  NaN
0          0    0
1          0    0
2          0    0
3          1    0
4          0    0
..       ...  ...
395        0    0
396        0    0
397        0    0
398        0    0
399        0    0

[400 rows x 2 columns]

In [170]:
dummy = dummy.rename(columns={np.nan: 'nan_col'})
# Apply the condition
dummy.loc[dummy['nan_col'] == 1, 'present'] = np.nan
object_cols[["pcc"]]=dummy[["present"]]

In [171]:
object_cols[["pcc"]].isnull().sum()

pcc    4
dtype: int64

In [172]:
object_cols[["pcc"]].value_counts()

pcc
0.0    354
1.0     42
Name: count, dtype: int64

In [173]:
dummy= pd.get_dummies(object_cols["ba"],drop_first=True,dtype=int,dummy_na=True)